import pathModule from 'node:path'

import type { ImageElement, Message } from 'node-karin'
import { db, karinPathHtml, logger, render, segment } from 'node-karin'
import type {
  DataTypeMap,
  DynamicRenderPath,
  ExtractDataTypeFromPath,
  TypedRenderRequest
} from 'template'
import reactServerRender from 'template'

import { Common, Root } from '@/module'
import { Config } from '@/module/utils/Config'

import { isSemverGreater } from '../semver'
import { createQrCodePlugin } from './plugins'
import { embedWatermark } from './wm'

type ImageMetadata = {
  width?: number
  height?: number
}

/**
 * 渲染函数
 * 将指定路径的模板渲染为图片元素数组
 * 
 * @param event 消息事件对象，用于获取机器人账号信息
 * @template P 渲染路径，必须是有效的动态路径
 * @param path 渲染路径，格式为 "平台/组件ID" 或 "平台/分类/组件ID"
 * @param data 渲染数据，类型根据路径自动推断
 * @returns 渲染结果图片元素数组的 Promise
 */
export const Render = async <P extends DynamicRenderPath> (
  event: Message,
  path: P,
  data?: ExtractDataTypeFromPath<P>
): Promise<ImageElement[]> => {
  const pathParts = path.split('/')
  let templateType: string
  let templateName: string

  if (pathParts.length === 2) {
    // 二级路径：platform/templateName
    [templateType, templateName] = pathParts
  } else if (pathParts.length === 3) {
    // 三级路径：platform/category/templateName
    templateType = pathParts[0]
    templateName = `${pathParts[1]}/${pathParts[2]}`
  } else {
    throw new Error(`不支持的路径格式: ${path}`)
  }

  const outputDir = pathModule.join(karinPathHtml, Root.pluginName, templateType)

  // 检查是否有可用更新
  let hasUpdate = false
  if (!Config.app.RemoveWatermark) {
    try {
      const UPDATE_LOCK_KEY = 'kkk:update:lock'
      const lockedVersion = await db.get(UPDATE_LOCK_KEY)
      if (typeof lockedVersion === 'string' && lockedVersion.length > 0) {
        // 锁定版本必须严格大于当前版本才认为有可用更新
        hasUpdate = isSemverGreater(lockedVersion, Root.pluginVersion)
      }
    } catch {
      // 忽略错误，默认无更新
    }
  }

  const renderRequest: TypedRenderRequest<keyof DataTypeMap> = {
    templateType: templateType as TypedRenderRequest<keyof DataTypeMap>['templateType'],
    templateName,
    scale: Math.min(2, Math.max(0.5, Number(Config.app.renderScale) / 100)),
    useDarkTheme: Common.useDarkTheme(),
    version: Config.app.RemoveWatermark ? undefined : {
      plugin: 'karin-plugin',
      pluginName: 'kkk',
      pluginVersion: Root.pluginVersion,
      releaseType: /^\d+\.\d+\.\d+$/.test(Root.pluginVersion) ? 'Stable' : 'Preview',
      poweredBy: 'Karin',
      frameworkVersion: Root.karinVersion,
      hasUpdate
    },
    data: {
      ...data,
      useDarkTheme: Common.useDarkTheme()
    }
  }

  // 调用 SSR 渲染，生成 HTML 文件
  const result = await reactServerRender({
    request: renderRequest,
    outputDir,
    plugins: [
      createQrCodePlugin()
    ]
  }).then(res => {
    if (!res.success || !res.htmlPath) {
      throw new Error(res.error)
    }
    return res
  }).catch(err => {
    throw new Error(`SSR渲染失败: ${err.message || '未知错误'}`)
  })

  // 截图渲染
  const renderResult = await render.render({
    name: `${Root.pluginName}/${templateType}/${templateName}`,
    file: result.htmlPath,
    multiPage: Config.app.multiPageRender ? Config.app.multiPageHeight : false,
    selector: '#container',
    fullPage: false,
    type: 'png',
    pageGotoParams: {
      waitUntil: 'load',
      timeout: Config.app.RenderWaitTime * 1000
    },
    omitBackground: true
  })

  const ret: ImageElement[] = []
  const images = Array.isArray(renderResult) ? renderResult : [renderResult]
  const imageStats: Array<{ index: number, type: 'png', sizeMb: string, dimensions: string }> = []

  for (const image of images) {
    const imageBuffer = Buffer.from(image, 'base64')
    const watermarkedBuffer = embedWatermark(
      imageBuffer,
      JSON.stringify({
        a: Date.now(),
        b: `Generated by karin-plugin-kkk v${Root.pluginVersion}, with source code open-sourced under the GPL-3.0 license`,
        c: `Sent by ${event?.bot?.account.selfId ?? 'unknown'}|${event?.bot?.account.name ?? 'unknown'}`
      })
    )
    const finalImageBuffer = watermarkedBuffer ?? imageBuffer
    const metadata = getImageMetadata(finalImageBuffer)
    const dimensions = metadata.width && metadata.height
      ? `${metadata.width}x${metadata.height}`
      : 'unknown'

    imageStats.push({
      index: ret.length,
      type: 'png',
      sizeMb: (finalImageBuffer.length / (1024 * 1024)).toFixed(3),
      dimensions
    })

    ret.push(
      segment.image(
        'base64://' + finalImageBuffer.toString('base64')
      )
    )
  }

  logger.debug(`[Render] 图片处理完成，准备入队发送: ${JSON.stringify(imageStats)}`)
  return ret
}

/**
 * 从图片缓冲区中提取元数据
 * @param buffer 图片缓冲区
 * @returns 图片元数据对象
 */
const getImageMetadata = (buffer: Buffer): ImageMetadata => {
  if (buffer.length >= 24 && buffer.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]))) {
    return {
      width: buffer.readUInt32BE(16),
      height: buffer.readUInt32BE(20)
    }
  }

  return {}
}
