import pathModule from 'node:path'
import { fileURLToPath } from 'node:url'

import { createTemplateRenderer, type DataOf, type LoadedRegistry } from '@karinjs/template-react'
import type { ImageElement, Message } from 'node-karin'
import { db, karinPathHtml, logger, render, segment } from 'node-karin'

import { Common, Root } from '@/module'
import { Config } from '@/module/utils/Config'

import { isSemverGreater } from '../semver'
import { createImagePathPlugin, createPosterPalettePlugin } from './plugins'
import { embedWatermark } from './wm'

/** 注册表类型：.ktr/registry-types.d.ts 模块增强生效后为逐路由精确类型。 */
type Registry = LoadedRegistry

/**
 * 动态渲染路径，格式为 "平台/组件ID" 或 "平台/分类/组件ID"。
 * 精确路由联合类型由 ktr 注册表的模块增强提供。
 */
export type DynamicRenderPath = keyof Registry & string

type ImageMetadata = {
  width?: number
  height?: number
}

// 开发态（tsx 跑 src/）捕获真实渲染数据到 template/<路由>/data/captured.json 供面板调试；
// 生产（lib/ 产物）显式关闭捕获，避免往已安装包里写文件。
const isDevRuntime = !fileURLToPath(import.meta.url)
  .replace(/\\/g, '/')
  .includes('/lib/')

// ktr 侧按约定装配（包根定位、karin.template.ts、.ktr 注册表、CSS 定位、捕获目录）；
// outputDir 与 htmlFileName 是 karin 领域的位置与命名，由插件显式指定。
const renderTemplate = createTemplateRenderer(import.meta.url, {
  bundledDir: 'lib',
  renderer: {
    outputDir: pathModule.join(karinPathHtml, Root.pluginName),
    htmlFileName: 'timestamp',
    plugins: [createImagePathPlugin(), createPosterPalettePlugin()],
    ...(isDevRuntime ? {} : { captureDir: undefined })
  }
})

/**
 * 渲染函数
 * 将指定路径的模板渲染为图片元素数组
 *
 * @param event 消息事件对象，用于获取机器人账号信息
 * @template P 渲染路径，必须是有效的动态路径
 * @param path 渲染路径，格式为 "平台/组件ID" 或 "平台/分类/组件ID"
 * @param data 渲染数据，类型根据路径自动推断
 * @options 渲染选项
 * @returns 渲染结果图片元素数组的 Promise
 */
export const Render = async <P extends DynamicRenderPath>(
  event: Message,
  path: P,
  // useDarkTheme 由各模板 Data 接口声明为可选字段，core 在这里统一注入，调用方无需关心
  data?: DataOf<Registry[P]>,
  options?: {
    /**
     * 是否跳过水印嵌入
     */
    skipWatermark?: boolean
  }
): Promise<ImageElement[]> => {
  const templateType = path.split('/')[0]

  // 检查是否有可用更新
  let hasUpdate = false
  if (!Config.app.RemoveWatermark) {
    try {
      const UPDATE_LOCK_KEY = 'kkk:update:lock'
      const lockedVersion = await db.get(UPDATE_LOCK_KEY)
      if (typeof lockedVersion === 'string' && lockedVersion.length > 0) {
        // 锁定版本必须严格大于当前版本才认为有可用更新
        hasUpdate = isSemverGreater(lockedVersion, Root.pluginVersion)
      }
    } catch {
      // 忽略错误，默认无更新
    }
  }

  const watermarkText = JSON.stringify({
    a: Date.now(),
    b: `Generated by karin-plugin-kkk v${Root.pluginVersion}, with source code open-sourced under the GPL-3.0 license`,
    c: `Sent by ${event?.bot?.account.selfId ?? 'unknown'}|${event?.bot?.account.name ?? 'unknown'}`
  })

  const watermarkTextBitSize = Buffer.byteLength(watermarkText, 'utf8') * 8
  const useDarkTheme = Common.useDarkTheme()

  // kkk 的模板上下文字段（version / watermarkTextBitSize / posterPalette）由 ktr 原样透传，
  // defineKkkTemplate 适配器再映射回组件 props。浅色不传 theme，与旧外壳输出保持一致。
  const ctx = {
    scale: Math.min(2, Math.max(0.5, Number(Config.app.renderScale) / 100)),
    version: Config.app.RemoveWatermark
      ? undefined
      : {
          plugin: 'karin-plugin',
          pluginName: 'kkk',
          pluginVersion: Root.pluginVersion,
          releaseType: /^\d+\.\d+\.\d+$/.test(Root.pluginVersion) ? ('Stable' as const) : ('Preview' as const),
          poweredBy: 'Karin',
          frameworkVersion: Root.karinVersion,
          hasUpdate
        },
    watermarkTextBitSize,
    ...(useDarkTheme ? { theme: { mode: 'dark' as const } } : {})
  }

  // 调用 ktr SSR 渲染，生成 HTML 文件；Object.assign 保留泛型推导（泛型对象 spread 会塌缩掉类型参数）
  const result = await renderTemplate(path, Object.assign({}, data, { useDarkTheme }), ctx)
    .then((res) => {
      if (!res.success || !res.htmlPath) {
        throw new Error(res.error)
      }
      return res
    })
    .catch((err: unknown) => {
      const message = err instanceof Error ? err.message : '未知错误'
      throw new Error(`SSR渲染失败: ${message}`)
    })

  // 截图渲染
  const renderResult = await render.render({
    name: `${Root.pluginName}/${templateType}`,
    file: result.htmlPath,
    multiPage: Config.app.multiPageRender && event.bot.adapter.protocol !== 'qqbot' ? Config.app.multiPageHeight : false,
    selector: '#container',
    fullPage: false,
    type: 'png',
    pageGotoParams: {
      waitUntil: 'load',
      timeout: Config.app.RenderWaitTime * 1000
    },
    omitBackground: true
  })

  const ret: ImageElement[] = []
  const images = Array.isArray(renderResult) ? renderResult : [renderResult]
  const imageStats: Array<{ index: number; type: 'png'; sizeMb: string; dimensions: string }> = []

  for (const image of images) {
    const imageBuffer = Buffer.from(image, 'base64')
    let finalImageBuffer: Buffer
    if (options?.skipWatermark) {
      finalImageBuffer = imageBuffer
    } else {
      finalImageBuffer = embedWatermark(imageBuffer, watermarkText) ?? imageBuffer
    }
    const metadata = getImageMetadata(finalImageBuffer)
    const dimensions = metadata.width && metadata.height ? `${metadata.width}x${metadata.height}` : 'unknown'

    imageStats.push({
      index: ret.length,
      type: 'png',
      sizeMb: (finalImageBuffer.length / (1024 * 1024)).toFixed(3),
      dimensions
    })

    ret.push(segment.image('base64://' + finalImageBuffer.toString('base64')))
  }

  const statsText = imageStats
    .map((stat, i) => `  [${i + 1}] 类型: ${stat.type}, 大小: ${stat.sizeMb}MB, 尺寸: ${stat.dimensions}`)
    .join('\n')
  logger.debug(`[Render] 图片处理完成，准备入队发送:\n共 ${imageStats.length} 张图片:\n${statsText}`)
  return ret
}

/**
 * 从图片缓冲区中提取元数据
 * @param buffer 图片缓冲区
 * @returns 图片元数据对象
 */
const getImageMetadata = (buffer: Buffer): ImageMetadata => {
  if (buffer.length >= 24 && buffer.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) {
    return {
      width: buffer.readUInt32BE(16),
      height: buffer.readUInt32BE(20)
    }
  }

  return {}
}

/**
 * 对已渲染的图片元素数组应用水印
 * 用于推送场景：渲染一次，按目标群逐个嵌入不同 bot 的水印
 */
export const applyWatermarkToImages = (images: ImageElement[], event: Message): ImageElement[] => {
  if (Config.app.RemoveWatermark) return images

  const watermarkText = JSON.stringify({
    a: Date.now(),
    b: `Generated by karin-plugin-kkk v${Root.pluginVersion}, with source code open-sourced under the GPL-3.0 license`,
    c: `Sent by ${event?.bot?.account.selfId ?? 'unknown'}|${event?.bot?.account.name ?? 'unknown'}`
  })

  return images.map((img) => {
    const base64Data = img.file.replace(/^base64:\/\//, '')
    const buffer = Buffer.from(base64Data, 'base64')
    const watermarked = embedWatermark(buffer, watermarkText) ?? buffer
    return segment.image('base64://' + watermarked.toString('base64'))
  })
}
