packages:
  - packages/*

onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@karinjs/sqlite3-cjs'
  - '@parcel/watcher'
  - '@swc/core'
  - cwebp-bin
  - esbuild
  - gifsicle
  - javascript-obfuscator
  - jpegtran-bin
  - mozjpeg
  - optipng-bin
  - pngquant-bin
  - sharp
  - unrs-resolver

publicHoistPattern:
  - '*sqlite3*'
  - '*express*'
