packages:
  - packages/*
  - packages/amagi/packages/core
  - packages/amagi/packages/response-types
  - packages/amagi/packages/typegen

overrides:
  node-karin: 1.18.0
  typescript: 7.0.2
  vite: 8.3.3

publicHoistPattern:
  - '*sqlite3*'
  - '*express*'
  - '@types/react'
  - '@types/react-dom'

minimumReleaseAge: 0

allowBuilds:
  '@swc/core': true
  esbuild: true
  sharp: true
