# 小红书解析开关，单独开关，受「总开关」影响
switch: true

# 小红书解析提示，发送提示信息：“检测到小红书链接，开始解析”
tip: true

# 解析时发送的内容，可选值：'info'(笔记、视频信息)、'comment'(评论图片)、'video'(视频文件)
sendContent:
  - 'info'
  - 'comment'
  - 'video'
  
# 小红书评论数量（预留）
numcomment: 10