/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function embedWatermarkToPngBytes(pngBytes: Buffer, watermarkText: string): Buffer

export declare function extractWatermarkFromPngBytes(pngBytes: Buffer): string
